name: Deploy Static HTML to Azure Web App

on:
  push:
    branches:
      - main  # or 'master' depending on your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload artifact for deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: eShopOnWeb
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
